-- Public-site copy managed through Admin > UI Translations.
insert into public.ui_translations (key, en) values
  ('home.kural', 'முயற்சி திருவினையாக்கும்'),
  ('home.visionHeading', 'Our Vision'), ('home.aboutHeading', 'About the Academy'),
  ('home.valuesTitle', 'Honesty. Discipline. Care.'), ('home.valuesText', 'How we run every classroom, every test, and every fee receipt.'),
  ('home.qualityTitle', 'Our Quality'), ('home.qualityText', 'Monthly tests with ranked results shared with parents, small batches of around 40, and teachers selected through live demonstration classes.'),
  ('home.coursesSubtitle', 'Expertly crafted programs designed to help you excel in your career'),
  ('home.eventsSubtitle', 'Stay updated with our upcoming and past events'), ('home.blogSubtitle', 'Insights, stories and updates from our academy'),
  ('home.ctaTitle', 'Ready to Start Your Journey?'), ('home.ctaText', 'Join Muyarchi Academy today and take the first step toward a brighter future.'), ('home.ctaButton', 'Get in Touch'),
  ('courseDetail.notFoundTitle', 'Course Not Found'), ('courseDetail.notFoundText', 'The course you are looking for does not exist.'),
  ('courseDetail.highlightsTitle', 'Course Highlights'), ('courseDetail.highlightsSubtitle', 'Key features of this program'),
  ('courseDetail.audienceTitle', 'Target Audience'), ('courseDetail.audienceText', 'Suitable for students aiming for this course preparation'),
  ('courseDetail.outcomesTitle', 'Learning Outcomes'), ('courseDetail.outcomesText', 'Comprehensive preparation with expert guidance and practice tests'),
  ('courseDetail.certificationTitle', 'Certification'), ('courseDetail.certificationText', 'Certificate provided upon successful completion'),
  ('courseDetail.ctaTitle', 'Ready to Enroll?'), ('courseDetail.ctaText', 'Join this course and start your journey towards academic excellence.'),
  ('eventDetail.notFoundTitle', 'Event Not Found'), ('eventDetail.notFoundText', 'The event you are looking for does not exist.'),
  ('eventDetail.overviewTitle', 'Event Overview'), ('eventDetail.overviewText', 'Complete details about this event'),
  ('eventDetail.dateLabel', 'Event Date'), ('eventDetail.venueLabel', 'Venue'),
  ('eventDetail.imageGallery', 'Image Gallery'), ('eventDetail.imageGalleryText', 'A visual journey through the event'),
  ('eventDetail.videoGallery', 'Video Gallery'), ('eventDetail.videoGalleryText', 'Watch highlights from the event'),
  ('eventDetail.ctaTitle', 'Interested in this Event?'), ('eventDetail.ctaText', 'Get in touch with us for more information about this event.'),
  ('contact.whatsappLabel', 'WhatsApp'), ('contact.openMapText', 'Open our location in Google Maps.'), ('contact.openMapButton', 'Open Google Maps'),
  ('form.enquiryOptions', 'Class 8|Class 9|Class 10|Class 11|Class 12|NEET|Engineering|Foundation|Spoken English|CMA|Government Exams'),
  ('form.classOptions', '8|9|10|11|12'), ('form.classPrefix', 'Class'), ('form.selectClass', 'Select class'), ('form.selectClassCourse', 'Select class or course'),
  ('form.studentNamePlaceholder', 'Enter student''s full name'), ('form.schoolPlaceholder', 'Current school name'), ('form.parentNamePlaceholder', 'Father/Mother/Guardian name'),
  ('form.phonePlaceholder', '10-digit mobile number'), ('form.townPlaceholder', 'Your town or village'), ('form.preferredTimePlaceholder', 'e.g., Morning 10 AM, Afternoon 3 PM, Evening 6 PM'),
  ('form.demoMessagePlaceholder', 'Any specific subjects or topics you''d like to cover in the demo?'),
  ('seo.title', 'Muyarchi Academy — Coaching Institute, Vaniyambadi'), ('seo.description', 'City-standard coaching in Vaniyambadi at fees families can afford.'),
  ('seo.keywords', 'Muyarchi Academy, coaching institute, Vaniyambadi, NEET coaching, Engineering entrance, Foundation classes, Spoken English, CMA'),
  ('seo.ogImage', '')
on conflict (key) do nothing;
